#!/usr/bin/env bash
# arbor-version-diff.sh — feature-discovery report between two CC versions,
# powered by Arbor (deep symbol/edge index + per-function literal extraction).
#
# Diffs only the STABLE signals — `tengu_*` telemetry events and slash-command
# names — because the minifier reassigns symbol names (XP1, C1q, $) every build,
# so a symbol-name diff is noise. Each NEW telemetry event is mapped to the
# function that emits it, via `arbor literals`, giving an anchor for deeper
# analysis (`arbor nearest-fn` / `arbor tree` / `arbor explain`).
#
# Usage:
#   ./scripts/arbor-version-diff.sh <from-version> <to-version> [output.md]
#   ./scripts/arbor-version-diff.sh 2.1.139 2.1.141
#   ./scripts/arbor-version-diff.sh 2.1.132 2.1.150 /tmp/span.md
#
# Env:
#   ARBOR_BIN      arbor binary (default: `arbor` on PATH; must support `literals`)
#   ARTIFACTS_DIR  bundle dir   (default: ../caludeCodeAVX2/artifacts, beside repo)
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <from-version> <to-version> [output.md]" >&2
  exit 1
fi
OLD="$1"
NEW="$2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ARTIFACTS_DIR="${ARTIFACTS_DIR:-$REPO_ROOT/../caludeCodeAVX2/artifacts}"
ARBOR_BIN="${ARBOR_BIN:-arbor}"
OUT="${3:-version-diff-${OLD}-${NEW}.md}"

OB="$ARTIFACTS_DIR/claude-$OLD.js"
NB="$ARTIFACTS_DIR/claude-$NEW.js"
for f in "$OB" "$NB"; do
  [[ -f "$f" ]] || { echo "ERROR: bundle not found: $f" >&2; exit 1; }
done
if ! "$ARBOR_BIN" literals --help >/dev/null 2>&1; then
  echo "ERROR: '$ARBOR_BIN literals' is unavailable." >&2
  echo "  Build/install Arbor with the literals command, e.g.:" >&2
  echo "    cargo install --path crates/arbor-cli   # in the Arbor repo" >&2
  echo "  or point ARBOR_BIN at a built binary:     ARBOR_BIN=/path/to/arbor $0 ..." >&2
  exit 1
fi
command -v python3 >/dev/null || { echo "ERROR: python3 is required" >&2; exit 1; }

W="$(mktemp -d)"
trap 'rm -rf "$W"' EXIT

echo "Indexing bundles with Arbor (this can take a few seconds per ~15MB bundle)…" >&2

# idx <bundle> -> "<symbols> <edges>"  (arbor index needs a directory)
idx() {
  local b="$1" d
  d="$(mktemp -d)"
  cp "$b" "$d/bundle.js"
  "$ARBOR_BIN" index "$d" 2>/dev/null | awk '
    /Symbols:/ { s = $2 }
    /^  Edges:/ { e = $2 }
    END { print s, e }'
  rm -rf "$d"
}
read -r OSYM OEDG < <(idx "$OB")
read -r NSYM NEDG < <(idx "$NB")

# Stable-signal sets.
tengu() { grep -oE 'tengu_[a-zA-Z0-9_]+' "$1" | sort -u; }
cmds()  { grep -oE '"[a-z][a-z0-9-]+",description:' "$1" | sed 's/",description:.*//; s/"//' | sort -u; }

tengu "$OB" > "$W/o.t"; tengu "$NB" > "$W/n.t"
comm -13 "$W/o.t" "$W/n.t" > "$W/added.t"
comm -23 "$W/o.t" "$W/n.t" > "$W/removed.t"

cmds "$OB" > "$W/o.c"; cmds "$NB" > "$W/n.c"
comm -13 "$W/o.c" "$W/n.c" > "$W/added.c"
comm -23 "$W/o.c" "$W/n.c" > "$W/removed.c"

# Map each NEW telemetry event to the function that carries it (Arbor literals).
"$ARBOR_BIN" literals "$NB" --output json 2>/dev/null > "$W/lits.json"
python3 - "$W/added.t" "$W/lits.json" "$W/evmap.tsv" <<'PYEOF'
import json, sys
added = {l.strip() for l in open(sys.argv[1]) if l.strip()}
data = json.load(open(sys.argv[2]))
idx = {}
for fn in data:
    for s in fn.get("strings", []):
        if s in added and s not in idx:
            idx[s] = (fn["function"], fn["location"]["start_line"])
with open(sys.argv[3], "w") as out:
    for ev in sorted(added):
        fn, ln = idx.get(ev, ("(no enclosing fn literal)", "-"))
        out.write(f"{ev}\t{fn}\t{ln}\n")
PYEOF

# ---- assemble the markdown report ----
n_add_t=$(wc -l < "$W/added.t" | tr -d ' ')
n_rem_t=$(wc -l < "$W/removed.t" | tr -d ' ')
n_add_c=$(wc -l < "$W/added.c" | tr -d ' ')
n_rem_c=$(wc -l < "$W/removed.c" | tr -d ' ')

{
  echo "# Arbor version-diff feature-discovery — Claude Code $OLD → $NEW"
  echo
  echo "> Generated by \`scripts/arbor-version-diff.sh\` ($(date -u +%Y-%m-%dT%H:%MZ)) using Arbor"
  echo "> (full index + per-function \`literals\`). Based on **stable literal signals**"
  echo "> (telemetry events, command names) — minified symbol names are reassigned per build and excluded."
  echo
  echo "## 1. Scale"
  echo
  echo "| | $OLD | $NEW | Δ |"
  echo "|---|---:|---:|---:|"
  echo "| symbols | $OSYM | $NSYM | $(printf '%+d' "$(( NSYM - OSYM ))") |"
  echo "| edges | $OEDG | $NEDG | $(printf '%+d' "$(( NEDG - OEDG ))") |"
  echo
  echo "## 2. New telemetry events ($n_add_t) — new / changed feature signals"
  echo
  if [[ "$n_add_t" -gt 0 ]]; then
    echo "Each event mapped to the function that emits it — dig deeper with"
    echo "\`arbor nearest-fn\` / \`arbor tree\` / \`arbor explain\` on that function."
    echo
    echo "| new event | emitting fn | line |"
    echo "|---|---|---:|"
    while IFS=$'\t' read -r ev fn ln; do echo "| \`$ev\` | \`$fn\` | $ln |"; done < "$W/evmap.tsv"
  else
    echo "_(none)_"
  fi
  echo
  echo "## 3. Removed telemetry events ($n_rem_t)"
  echo
  if [[ "$n_rem_t" -gt 0 ]]; then
    while read -r ev; do echo "- \`$ev\`"; done < "$W/removed.t"
  else
    echo "_(none)_"
  fi
  echo
  echo "## 4. Slash commands"
  echo
  echo "- **Added ($n_add_c):** $( [[ "$n_add_c" -gt 0 ]] && sed 's#^#/#' "$W/added.c" | paste -sd', ' - || echo '_(none)_' )"
  echo "- **Removed ($n_rem_c):** $( [[ "$n_rem_c" -gt 0 ]] && sed 's#^#/#' "$W/removed.c" | paste -sd', ' - || echo '_(none)_' )"
  echo
  echo "---"
  echo "_Notes: \`tengu_\` = telemetry / feature flag. Codename-style events (e.g. \`amber_*\`, \`*_lark\`)_"
  echo "_are usually A/B experiment toggles. Prose still comes from the LLM interpretation step;_"
  echo "_Arbor supplies the structural evidence (which function, which calls, which constants)._"
} > "$OUT"

echo "Wrote $OUT" >&2
echo "  scale: ${OSYM}→${NSYM} symbols, ${OEDG}→${NEDG} edges | +${n_add_t}/-${n_rem_t} telemetry | +${n_add_c}/-${n_rem_c} commands" >&2
